#! /usr/bin/env python
import csv

def get_stuff(filename):
    with open(filename) as fh:
        data = fh.readlines()
    data = csv.reader(data)
    return data

def get_station_names(filename):
    data = get_stuff(filename)

    stations = [row[0] for row in data]

    return stations

def basic_game(guess, stations):
    if guess in stations: 
        if is_mornington(guess):
            win()
        else:
            guess_again(guess)
    else:
        lose()


def game_loop(station_file):
    station_list = get_station_names(station_file)

    while True:
        guess = raw_input('So, which station are you thinking of? ')
        basic_game(guess.strip())

if __name__ == '__main__':
    game_loop('stations.csv')
