#! /usr/bin/env python3
import csv
import sys

def get_stuff(filename):
    with open(filename) as fh:
        data = fh.readlines()
    data = csv.reader(data)
    return data


def get_station_names(filename):
    data = get_stuff(filename)

    stations = [row[0] for row in data]

    return stations

def is_mornington(station):
    return station == "Mornington Crescent"


def win():
    print("You have won!")
    sys.exit()


def lose():
    print("You lose :'(")
    sys.exit()


def basic_game(guess, stations):
    if guess in stations: 
        if is_mornington(guess):
            win()
        else:
            print('{guess} is not what I was thinking of'.format(guess=guess))
    else:
        lose()


def game_loop(station_file, rules):
    station_list = get_station_names(station_file)

    while True:
        guess = input('So, which station are you thinking of? ')
        rules(guess.strip(), station_list)


if __name__ == '__main__':
    rules = 'basic'
    if len(sys.argv) > 1:
        selection = sys.argv[1]
    rules = {
        'basic': basic_game,
    }
    selected_rules = rules.get(selection)
    if selected_rules:
        game_loop('stations.csv', selected_rules)
    else:
        sys.stderr.write(
            'You need to pick a valid rules-set: {choices}\n'.format(
                choices=', '.join(rules.keys()),
            )
        )
        sys.exit(1)
