#! /usr/bin/env python
import csv

def get_stuff(filename):
    with open(filename) as fh:
        data = fh.readlines()
    data = csv.reader(data)
    return data

def get_station_names(filename):
    data = get_stuff(filename)

    stations = [row[0] for row in data]

    return stations

if __name__ == '__main__':
    print(get_station_names('stations.csv'))
